### ISSUE TITLE
Track information leakage

### ISSUE THREAD

**Issue by dethe** [mozilla/lightbeam#123]
Ashkan pointed out this story about how websites can inadvertently leak user data to tracking sites: http://bits.blogs.nytimes.com/2012/11/01/romney-and-obama-campaigns-leaking-web-site-visitor-data/

We could add some capability to Collusion for detection and showing this type of leakage. It has been added to https://mobilescope.net/ and Ashkan is happy to discuss that further.

**Comment by fmarier** [comment]
This is partly done via the new "tracking protection" option in Lightbeam 1.2.0.
