### ISSUE TITLE
French Localization on AMO

### ISSUE THREAD

**Issue by Cameleon** [mozilla/lightbeam#146]
I'd like to propose a french localisation of your presentation page on AMO.

Short presentation:
Ce module vous permet de visualiser qui vous piste en temps réel et de comprendre comment fonctionne la publicité ciblée.

About this module:
Collusion est un projet expérimental pour Firefox qui vous permet de voir quels sites utilisent des cookies tiers pour suivre vos mouvements sur le Web. Collusion montre, en temps réel, comment ces données créent une toile d'araignée et les interactions entre les entreprises et les autres "pisteurs".

Si vous ne voyez pas l'icône de collusion dans le coin inférieur droit de votre navigateur, assurez-vous que la barre d'add-on est affichée. Sous Windows, cliquez sur le bouton de menu Firefox, puis cliquez sur Options, puis cochez la case "Barre des modules". Sur Mac, allez dans le menu Affichage, puis dans le menu Barres d'outils, puis cochez la case "Add-on Bar".

Nous travaillons sur l'ajout de plus de fonctionnalités, comme la possibilité de télécharger une version anonyme de vos données collusion afin que nous puissions construire une vue d'ensemble de l'écosystème des pisteurs. Nous travaillons également sur ​​la visualisation d'autres méthodes de suivi des cookies tiers et à l'amélioration des visualisations en général. Si vous souhaitez garder un oeil sur nos progrès, signaler un bogue, demander une fonctionnalité, ou obtenir une copie du code source, visitez https://github.com/mozilla/collusion ou notre page wiki https://wiki.mozilla.org/Collusion.

**Comment by fmarier** [comment]
Done in #454.
