### ISSUE TITLE
Try dial visualization with a lighter ground

### ISSUE THREAD

**Issue by k88hudson** [mozilla/lightbeam#157]
@amberfj mentioned that the current plans for a colour scheme in #150 might be too dark for the new dial/day view visualization that is prototyped in the `c2/` directory.  We should consider try converting the stage to a slightly lighter ground for this visualization.

Additionally, it will likely need a distinct colour scheme from the existing red/blue visualization.

**Comment by fmarier** [comment]
The Clock view has been removed.
