### ISSUE TITLE
Add a Collusion "Third Party Ranking" to each "Server Profile" in the Collusion Directory

### ISSUE THREAD

**Issue by amberfj** [mozilla/lightbeam#190]
Using the Google Analytics profile as an example --> http://collusionweb-development.herokuapp.com/third-party-websites/google-analytics.com 

Add a Collusion "Third Party Ranking" for each server profile below the map:

Google Analytics ranks [12]th out of [210] total third party servers profiled by Collusion users' shared data.

[Visual bar graph showing Google Analytic's Third party ranking on a per day basis over its history]

[caption] Bar graph showing Google Analytic's Collusion third party ranking as it has changed since it first appeared in the Collusion public data set on the XX day of [month] [year]. 

[tooltip explaining "Collusion third party ranking"] The Collusion third party ranking is based on the number of third party connections that this server has made relative to all other servers profiled by Collusion users' shared data to date.

**Comment by fmarier** [comment]
We no longer send the data to our servers, so we cannot produce this ranking anymore.
