### ISSUE TITLE
Disabling cookies results in no change to Collusion graph

### ISSUE THREAD

**Issue by toolness** [mozilla/lightbeam#20]
If a user turns off support for cookies, deletes all existing cookies and restarts Firefox, the collusion graph doesn't change much (or at all).

This is because Collusion's code actually looks for *either* a `Cookie:` header in the HTTP requests Firefox sends out *or* a `Set-Cookie:` header in the HTTP response to determine whether a link should be created in the Collusion graph. Even when cookies are disabled, the `Set-Cookie:` header is still provided by remote servers, which is why the graph still indicates that you're being tracked.

We might be able to fix this by talking to Firefox's cookie manager instead of (or in addition to) just inspecting HTTP requests/responses. Or I suppose we could ignore `Set-Cookie:` headers in responses entirely, and only create graph links when `Cookie:` is in the request header.

**Comment by fmarier** [comment]
These comments are from an old version of the add-on and I suspect it's been fixed since. Please feel free to re-open this bug if it's still a problem. Thanks!
