### ISSUE TITLE
Opacity of site menu

### ISSUE THREAD

**Issue by Farscaper** [mozilla/lightbeam#213]
First let me say I love the beautiful imagery and concept but I find it difficult to view the site info text when I can so clearly see the background underneath. 

Might I suggest darkening it to the same level as seen on the Reset/Export/Zoom dropdown. I also see no reason to have even those menu items lighten when hovered over since the same problem occurs when you do. Perhaps just pick an opaqueness that is fairly transparent but still user friendly.

You might also consider adding a longer title so that more than just Collusion shows in the browser header. ie: Collusion: Cookie tracking tag cloud for Firefox.

I'm not dev so I only generate opinions, not code. Hope it helps.

**Comment by fmarier** [comment]
I think that these comments are based on a really old version of the add-on. Please feel free to re-open this bug if it's still a problem in recent version of Lightbeam.
