### ISSUE TITLE
Also read Flash cookies, if possible

### ISSUE THREAD

**Issue by jonoxia** [mozilla/lightbeam#22]
Flash cookies are a major means of tracking people on the web; Collusion doesn't currently know about them. I'm not sure how much data we can actually get from the plugin about the individual cookies it's storing and what sites it allows to have them. Will need to do some research on that.

**Comment by fmarier** [comment]
By the time we get to this, I suspect Flash will be mostly click-to-play, so we may as well focus on other things.
