### ISSUE TITLE
Remove Collusion, then undo, still removes Collusion

### ISSUE THREAD

**Issue by dethe** [mozilla/lightbeam#249]
[Reported by Aleksej here: https://bugzilla.mozilla.org/show_bug.cgi?id=890276#c1]

But (with 22.0) if I remove it and undo removal, the icon doesn't re-appear.

Also, with 23.0 Beta and the Nightly, if I use it and then remove, Navigation Bar disappears and cannot be enabled until restart.

As in, does not re-appear after about:addons.

Aleksej: please see https://bugzilla.mozilla.org/show_bug.cgi?id=890276
Aleksej: The reporter closed the bug, but my comment was not about private browsing.
dethe: So the problem is, if you remove the icon from the add-on bar, there is no way to get it back?
Aleksej: I haven't removed the icon.
Aleksej: I think I clicked "remove" in the about:addons, then clicked "Undo".
Aleksej: The icon didn't appear like it does on install.
Aleksej: (That's nothing compared to navbar disappearing though 
dethe: And the add-on bar disappeared? So two different issues, both unrelated to the original. I'm just trying to keep this straight.
Aleksej: I haven't debug the icon issue…
Aleksej: will try now
Aleksej: The add-on bar is not there when the icon is not there.
Aleksej: Maybe unremoving is not processed as installing
Aleksej: Disappearing navbar is easy to reproduce if you don't undo removal.
Aleksej: But you have to use Collusion / click its icon.
Aleksej: There are tracebacks in the terminal.

**Comment by fmarier** [comment]
This is fixed in Lightbeam 1.2.1.
