### ISSUE TITLE
Sharing Data Feedback System

### ISSUE THREAD

**Issue by sabrinang** [mozilla/lightbeam#318]
Design system for people to opt in to donate data. (notification after x amount of time using collusion? Include description (includes: explain why, what they see, non profit, to help build database and what they can do about it and don't show this again)

Design incentive system? How can we make people feel good about sharing and what can motivate users to share? (feedback, gamification, rewards etc.)

**Comment by fmarier** [comment]
This code has been removed from Lightbeam and the server receiving the data has been shut down.
