### ISSUE TITLE
Integrate browser fingerprinting data i.e. "how unique is my useragent"

### ISSUE THREAD

**Issue by jonoxia** [mozilla/lightbeam#34]
Look at say http://panopticlick.eff.org  which shows how unique your browser fingerprint is based on all the bits of entropy that it reports to any website that asks.

This could be integrated right into Collusion - it could tell the user "Your browser fingerprint is very likely to be unique". We don't know for sure, of course, so this would have to be a heuristic.

Maybe provide some options for the user to turn off some of the reporting features that expose those bits of entropy?

**Comment by fmarier** [comment]
This sounds like a different problem that what Lightbeam is solving (or exposing).

Very worthwhile thing to do, but I don't think it's a good fit for Lightbeam.
