### ISSUE TITLE
Collusion button and menu option do not appear anywhere

### ISSUE THREAD

**Issue by mvac** [mozilla/lightbeam#347]
After installing Collusion 0.27 on Firefox 22.0 (Linux; x86_64) there's no Collusion button next to the buttons of other add-ons, there's no Collusion button in the add-on bar, and there is no Collusion Graph option in the Tools menu. The only place I've found Collusion so far is the Add-ons Manager.

Edit: spelling

![ff collusion](https://f.cloud.github.com/assets/5074345/942131/089ffc60-017e-11e3-8d2b-b9c9fba13913.png)

**Comment by fmarier** [comment]
This should be resolved now that Australis has landed.
