### ISSUE TITLE
List View: Clear groups of selected checkboxes

### ISSUE THREAD

**Issue by sabrinang** [mozilla/lightbeam#426]
From discussion from issue #413, check box user expectations and functionality:
![collusion - checkboxgroupdeselect](https://f.cloud.github.com/assets/2492510/1141716/2bc09aea-1cba-11e3-8f5e-2d49840335bf.jpg)

Suggestion for the *Clear all selected* text function in context below the site selected feedback line in issue #422 :
![collusion - checkboxgroupdeselect_ui](https://f.cloud.github.com/assets/2492510/1141721/55e4daf2-1cba-11e3-867c-84dc5ec9faa0.jpg)

**Comment by fmarier** [comment]
Fixed in #442.
