### ISSUE TITLE
List sorting arrows are flipped

### ISSUE THREAD

**Issue by acdha** [mozilla/lightbeam#453]
In the list view, the sort direction arrow shows the direction which clicking on the header will change to rather than the currently order. In the screenshot below, the list is sorted in descending order based on the number of connected sites but the arrow is shown pointing up.

![screen shot 2013-10-25 at 12 13 56 pm](https://f.cloud.github.com/assets/46565/1409302/bb55f2da-3d90-11e3-84c6-db66acc54db3.png)

**Comment by fmarier** [comment]
This is still a bug in Lightbeam 1.2.1.
