### ISSUE TITLE
Downloaded and Nada, Zip, Zero, can't find it. 

### ISSUE THREAD

**Issue by DamascusSteele** [mozilla/lightbeam#460]
I downloaded this add on. It seemed like a good thing to know who is watching. After downloading it twice once just download and couldn't find it anywhere, even global search finds nothing.  The second time I downloaded it onto the browser bar and still nothing.

**Comment by fmarier** [comment]
Probably fixed in the latest version of Lightbeam and Firefox. Feel free to reopen this bug if you're still experiencing this problem.
