### ISSUE TITLE
Lightbeam does nothing

### ISSUE THREAD

**Issue by glnzglnz** [mozilla/lightbeam#463]
There's nothing in the big black space all the time.  And most of the little links at bottom do nothing.

I use NoScript.  If Lightbeam has a problem with NoScript, then Lightbeam needs to change.

Thanks.

**Comment by fmarier** [comment]
Is this still happening with Lightbeam 1.1.1 and Firefox 35?

**Comment by fmarier** [comment]
The cookie issue is tracked in #490 and I've just filed #668 to warn about history being disabled.

As far as I can tell, these are the underlying issues behind this bug report.
