### ISSUE TITLE
Corrections to Lightbeam About page

### ISSUE THREAD

**Issue by dethe** [mozilla/lightbeam#473]
[From @amberfj via email]

I'm writing to request a slight change to the text that pertains to Emily Carr on the Lightbeam About page: 
http://www.mozilla.org/en-US/lightbeam/about/

Here's what we'd like changed in the "Origins of Lightbeam" section: 
Third paragraph first sentence should read:
"In September 2012, Mozilla joined forces with faculty and student researchers..." instead of "students".
Also please change the link at the bottom of the section to:
"To read more about the collaboration, please visit http://research.ecuad.ca/lightbeam " instead of "http://simcentre.ca"

**Comment by fmarier** [comment]
This was merged in bedrock a while ago.
