### ISSUE TITLE
UI unresponsive, "Security error: the operation is insecure" on localStorage accesses

### ISSUE THREAD

**Issue by zackw** [mozilla/lightbeam#475]
I have Lightbeam 1.0.2 (the current version on AMO) with Firefox Beta (26.0b2 as of today).  The visualization screen loads, but displays no data, and all of the buttons in the UI are unresponsive to clicks (except the "about lightbeam" [i] clicky, which works).

Right after the screen loads, there are four errors in the Web Console for the visualization screen:

> 16:29:17.627 SecurityError: The operation is insecure. aggregate.js:465
> 16:29:17.631 SecurityError: The operation is insecure. ui.js:45
> 16:29:17.637 SecurityError: The operation is insecure. list.js:493
> 16:29:17.887 SecurityError: The operation is insecure. collusion.js:93

Inspection of the offending lines tells me that the only thing they have in common is access to the localStorage object.

If I leave it a little longer, another error appears:

> TypeError: currentVisualization is undefined clock.js:398

but I presume that this is fallout.

In case this is some weird interaction with another extension, here is my full set of extensions:

    Name                                    Version   Enabled   ID
    Adblock Plus                            2.4       true      {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
    Always Awesome Bar                      1.0.1     true      alwaysawesomebar@kaply.com
    Cookie Whitelist, With Buttons          2.2.1     true      cwwb@dietrich.cx
    Custom Standalone Image Backgrounds     0.5       true      customstandaloneimagebackgrounds@girish.sharma
    Firebug                                 1.12.4    true      firebug@software.joehewitt.com
    Google/Yandex search link fix           1.4.1     true      jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack
    IdentFavIcon                            0.3.4.7   true      identfavicon@david.hanak.hu
    Lightbeam                               1.0.2     true      jid1-F9UJ2thwoAm5gQ@jetpack
    Link Widgets                            1.7.0.1   true      linkwidget@clav.mozdev.org
    Open in Browser                         1.11      true      openinbrowser@www.spasche.net
    Saved Password Editor                   2.7.1     true      savedpasswordeditor@daniel.dawson
    Secure Password Generator               0.5       true      password.generator@kolya.ca

**Comment by fmarier** [comment]
Are you still seeing this problem in Lightbeam 1.2.1?

I've never seen it myself.

**Comment by zackw** [comment]
The current version of Lightbeam seems to work fine.
