### ISSUE TITLE
Switching between Graph/Clock/List freezes browser for 10sec

### ISSUE THREAD

**Issue by digitarald** [mozilla/lightbeam#476]
Graph also stutters badly and renders with only 5fps.

Clock: https://cloudup.com/cDcXK74taUi
Graph: https://cloudup.com/cZPGnXuIaUt

One idea would be to replace d3 with a simple (asm.js) spring physics library. Can the data crunching be done on a worker to not block the UI thread?

**Comment by fmarier** [comment]
I'll assumed this has been fixed, please feel free to re-open if you're still experiencing this problem.
