### ISSUE TITLE
Incorrect Toggle for Contribute Data After browser restart (display tabs from last time)

### ISSUE THREAD

**Issue by PantherX** [mozilla/lightbeam#477]
I have configured Firefox to "Show my windows and tabs from last time" and if I restarted the browser without closing the LightBeam tab, upon restart, the toggle is incorrectly set to Off. If I click on it again to toggle it to the On position, I get a message indicating that I am turning off the data sharing. I have attached the screenshot indicating this error.
![incorrect contribute data toggle](https://f.cloud.github.com/assets/5349122/1516480/0e923bc0-4b15-11e3-8b54-0c84f73c7407.PNG)

**Comment by fmarier** [comment]
We removed the data upload feature in e73b479fdb7d99359f35688a7f540e4fbcc80d12.
