### ISSUE TITLE
missing connectors

### ISSUE THREAD

**Issue by dr-zin** [mozilla/lightbeam#484]
Seems that everything works except that the circles are not connected with the direction lines. When it was Collusion everything was there. FF 25.0.1, Win 7

**Comment by fmarier** [comment]
Is that still happening with Lightbeam 1.1.1 and Firefox 35?

**Comment by dr-zin** [comment]
Greetings Francios;
Just got your question.
Am now using FF Ver. 35 and Lightbeam 1.1.1
I have now tried it and the "connectors" do show.
Great, long time coming though, LOL.....

Respectfully;
R.(Ray)G. Zinn
"No electrons have been harmed in creating this message"
"Made from 100% recycled bits, bytes, & electrons"
"The tone and tendency of liberalism...is to attack the institutions of the country
under the name of reform and to make war on the manners and customs (and freedom) of
the people under the pretext of progress." --Disraeli,

**Comment by fmarier** [comment]
Thanks for double-checking @dr-zin, sorry it took so long!
