### ISSUE TITLE
Lightbeam is simply blank

### ISSUE THREAD

**Issue by tahl20** [mozilla/lightbeam#485]
When I first downloaded Lightbeam it worked great. I haven't checked in for a couple weeks, but thought I would tonight and it's totally blank. It says I haven't visited any sites etc... all while having a dozen tabs open over 3 windows.

I have tried disabling add-ons, but that didn't correct it. Tried restarting after disabling the add-ons, and that also didn't work. I also tried removing lightbeam and then reinstalling it. I'm sorry, but I do not know at what point it stopped working.

**Comment by fmarier** [comment]
I believe the issues affecting Firefox 34 were fixed in #637. Please feel free to file a new bug if you're still having problems.
