### ISSUE TITLE
Lightbeam is filling message log with GetDomain() messages looking for my gateway

### ISSUE THREAD

**Issue by greyghoster** [mozilla/lightbeam#489]
When started Gnome is filling my log with: 
Dec 27 10:44:42 frank gnome-session[2123]: getDomain(): ip address: 192.168.0.2 Dec 27 10:44:42 frank gnome-session[2123]: console.error: lightbeam: 
I have since disabled it but filling start again if I enable Light beam again.

**Comment by fmarier** [comment]
I haven't seen these errors messages lately so I think this is fixed.

If you still see them, please feel free to reopen this bug.
