### ISSUE TITLE
Icon changes location when Firefox restarted

### ISSUE THREAD

**Issue by JohnRS** [mozilla/lightbeam#491]
I added a custom toolbar then moved the Lightbeam icon to it.  Whenever I restart Firefox the Lightbean icon has relocated itself to the Add-on bar, and anything which was following it on my custom toolbar has been relocated to the Customize Toolbar menu.

Note:  If I move the Lightbeam icon to the Navigation bar instead, it seems to remain.

Thanks.

**Comment by fmarier** [comment]
This should no longer be a problem on Australis.
