### ISSUE TITLE
on startup, content process shouldn't wait to get the entire graph to start drawing

### ISSUE THREAD

**Issue by monicachew** [mozilla/lightbeam#525]
From https://addons.mozilla.org/en-US/firefox/users/login?to=/en-US/firefox/addon/lightbeam/reviews/565822, graph doesn't load until tab is closed and re-opened. This needs verification.

**Comment by zistrosk** [comment]
Above, it says "This needs verification."  I can verify this is indeed the case.  I just installed Lightbeam v1.3.2.  I clicked on the little button to open it, watched it for a while.  Then I copied and pasted the url for it and added it to my homepage.  Closed and opened the browser, and while the Lightbeam tab opened, there was no display of data, and all the buttons were disabled (or at least, clicking on them did nothing at all).  I clicked the little lightbeam button, and the tab that opened with the browser closed.  Clicked it again, and another tab opened, with the SAME URL I had copied and pasted to my homepage (so, the url I'm using isn't wrong), and then it started graphing relationships like it's supposed to.  Does adding the Lightbeam url to my home page make it "start too early" somehow, so it's not ready?  I like Lightbeam, but it would be far more useful to me if I was sure that it was collecting data from the second the browser opens, and I don't have to remember to click a button to open its tab.  I'd like it to already be open and ready for inspection whenever I feel like clicking on it's already-open tab.  Thanks for a great product, and keep up the good work!  --Zistrosk

**Comment by jonathanKingston** [comment]
This I think still is an issue in: https://github.com/mozilla/lightbeam-we however we can now query the indexedDb in a time based manner to fix this. Currently the performance is improved a lot anyway.

I'm going to close this here and we can re-raise in the new repo perhaps.

**Comment by zistrosk** [comment]
Thanks Jonathan!  I appreciate you looking into the issue!

Gary

On Thu, Sep 28, 2017 at 7:48 PM, Jonathan Kingston <notifications@github.com
