### ISSUE TITLE
cannot find icon for lightbeam

### ISSUE THREAD

**Issue by RBP610** [mozilla/lightbeam#541]
I believe lightbeam is a great add on. I had downloaded it twice and cannot find the icon any where on my computer. What am I doing wrong? Is they a place on my computer where I can find it and make it appear on my toolbar?
Thanks for  any help you or anyone in your community (if you have one) can give me on this issue.

Bov

**Comment by fmarier** [comment]
The original issue should be solved and the e10s bug is tracked in bugzilla.
