### ISSUE TITLE
import promise library

### ISSUE THREAD

**Issue by monicachew** [mozilla/lightbeam#555]
DOM promises are available in FF 29.

We had a race condition in the content scripts caused by two reset events (one of which called onLoad) that caused global.allConnections[] to be cleared incorrectly. Right now the "solution" is to sleep, but we can avoid that by using promises.

**Comment by jonathanKingston** [comment]
We now use native promise with async/await in the new Lightbeam 2.0.0: https://github.com/mozilla/lightbeam-we so closing 📯
