### ISSUE TITLE
Resetting the data doesn't work

### ISSUE THREAD

**Issue by thisguy1** [mozilla/lightbeam#562]
When pressing the "Reset Data" button after a few hundred websites are in the list, Lightbeam starts to act really strange. When you first open it, it shows that there is no data, but when you open it a second time it shows all the data that should have been deleted (even after restarting the browser). Resetting the data works however after you press the "Reset Data" button serveral times.

**Comment by jonathanKingston** [comment]
We just migrated to https://github.com/mozilla/lightbeam-we try it out, it should solve this issue.
