### ISSUE TITLE
Missing graph

### ISSUE THREAD

**Issue by SirWumpus** [mozilla/lightbeam#568]
Firefox 29.0; There is no graph displayed as I move around sites. In the past this was because I typically disable the Referer header (network.http.sendRefererHeader) for privacy; but it is currently reset to the default enabled and there is no graph or other visible items in the central view area.

**Comment by fmarier** [comment]
Is this still a problem with Lightbeam 1.1.1 and Firefox 35?

**Comment by MHWallace** [comment]
Francois - No, that issue has been resolved.Using those versions of each 
application. MHWallace.

**Comment by fmarier** [comment]
Thanks for double-checking @MHWallace!

**Comment by MHWallace** [comment]
You're welcome. Glad to help.
