### ISSUE TITLE
Unresponsive script warning

### ISSUE THREAD

**Issue by garrettr** [mozilla/lightbeam#572]
When I open Lightbeam in my normal FF profile, the new tab loads but the graph stays blank for several seconds, during which period the entire browser is frozen and no UI interaction can be made. Eventually, I get an alert dialog that says:

```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: resource://jid1-f9uj2thwoam5gq-at-jetpack/lightbeam/data/aggregate.js:115
```

Clicking "Continue" results in a few more seconds of jank, followed by the graph rendering properly and the jank going away.

I think we may need to consider re-architecting the graph generation to avoid this jank. The script warning is especially bad - if you hit "Cancel" instead of "Continue", the graph never renders and Lightbeam is useless.

**Comment by fmarier** [comment]
I haven't seen this in a while, so I'll assume it's no longer an issue.

General performance problems are tracked in #582.
