### ISSUE TITLE
Lightbeam slows down page loads

### ISSUE THREAD

**Issue by garrettr** [mozilla/lightbeam#582]
Running lightbeam seems to noticeably slow down page loads, especially on pages with lots of 3rd party resources. While of course some amount of latency is inevitable, I think we can probably do better.

The first thing to do here should be to log page load times with and without the lightbeam code running for each request (to do without, just early return in Lightbeam's observer). If the difference is significant, we should look for ways to reduce the latency.

**Comment by jonathanKingston** [comment]
We should performance check https://github.com/mozilla/lightbeam-we the new repo, however I can confirm it is vastly improved.
