### ISSUE TITLE
Website Profiles aren't working

### ISSUE THREAD

**Issue by SinisterSolace** [mozilla/lightbeam#612]
When I select a website on lightbeam it doesn't open the profile and panel and I can't find any other ways of opening it. The profile panel tab is also greyed out.

**Comment by fmarier** [comment]
@SinisterSolace Is that still a problem in version 1.2.1?

**Comment by jonathanKingston** [comment]
This panel is currently removed in 2.0.0, we likely will add this back in however this should be tracked here: https://github.com/mozilla/lightbeam-we

Thanks!
