### ISSUE TITLE
Latest Firefox has issues with downloading and with FaceBook

### ISSUE THREAD

**Issue by Mikelyons85** [mozilla/lightbeam#615]
Hi,
I am experiencing problems with FF in FB and when downloading files from the web. File download results in multiple tabs appearing across the top of the FF window. This can be stopped by pressing ESC, but the file fails to download. I keep having to return to IE. Yuk!

The issue with FB is that text typed (particularly if errors are made and the backspace key is used) usually results in gibberish. The words are broken and rearranged and the apostrophe doesn't work. This effect doesn't appear in any other  application or website that I use, including twitter and pinterest.

Any ideas?

**Comment by fmarier** [comment]
Hi @Mikelyons85, I doubt your problem with Firefox has anything to do with the Lightbeam add-on. I would suggest you ask your question on https://support.mozilla.org.
