### ISSUE TITLE
Lightbeam triggers tons of warning-spam in latest Nightly: "WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts)."

### ISSUE THREAD

**Issue by dholbert** [mozilla/lightbeam#616]
STR:
 1. Start nightly from the terminal (so you can see warning messages that go to the terminal).

 2. Install Lightbeam from
   https://addons.mozilla.org/en-US/firefox/addon/lightbeam/

 3. Open a new tab, e.g. https://www.google.com/ or https://yahoo.com

ACTUAL RESULTS: A bunch of copies of this message are spammed to your terminal:
{
WARNING: content window passed to PrivateBrowsingUtils.isWindowPrivate. Use isContentWindowPrivate instead (but only for frame scripts).
pbu_isWindowPrivate@resource://gre/modules/PrivateBrowsingUtils.jsm:25:14
getTabForChannel@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/foo21/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-f9uj2thwoam5gq-at-jetpack/lightbeam/lib/tab/utils.js:67:21
Connection.prototype.restoreFromSubject@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/foo21/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-f9uj2thwoam5gq-at-jetpack/lightbeam/lib/connection.js:149:11
Connection.fromSubject@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/foo21/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-f9uj2thwoam5gq-at-jetpack/lightbeam/lib/connection.js:98:3
@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///tmp/foo21/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-f9uj2thwoam5gq-at-jetpack/lightbeam/lib/main.js:27:20
Observer<.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/events.js:72:7
}

Version info:
Lightbeam 1.0.10.2
Nightly 35.0a1 (2014-09-30)
Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0

NOTE: This warning was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1069059 and indicates that the code needs to be changed.

**Comment by fmarier** [comment]
@dholbert suggests a fix on https://github.com/mozilla/lightbeam/pull/625#issuecomment-66811302
