### ISSUE TITLE
Unblocking blocked sites

### ISSUE THREAD

**Issue by kniick66** [mozilla/lightbeam#626]
Hi,
As a newbie, and not so tech savvy at all, I blocked many many sites who I paranoidly thought must be spying on me... guess what, now I cannot view many things via the mozilla browser, including certain youtube stuff, educational stuff etc..

thing is, I have been searching how to unblock the site Ive blocked=-- to no avail, I cannot find out how, or even which sites I have blocked..

ANy tips or help would be most welcome

thanks

Nick

**Comment by fmarier** [comment]
Version 1.1.1 has been released and it brings back the buttons at the bottom of the list view to block/unblock sites: https://addons.mozilla.org/en-US/firefox/addon/lightbeam/
