### ISSUE TITLE
Remove the privacy policy

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#650]
Now that we're no longer collecting data, we may not need a privacy policy. We should check with legal.

If that's the case, then we can remove it from:
- the add-on
- the AMO page

At the very least, we should remove the copy of the policy from the add-on and link to the web copy of it, as suggested by @monicachew on https://github.com/mozilla/lightbeam/pull/644#issuecomment-70756181.

**Comment by jonathanKingston** [comment]
No privacy policy was added to the new repo. Closing.
