### ISSUE TITLE
Karan

### ISSUE THREAD

**Issue by karandhankhar** [mozilla/lightbeam#653]
Intenett is not running properly  and firefox also not working properly.

**Comment by fmarier** [comment]
I would suggest going to https://support.mozilla.org for help since your problems probably don't have anything to do with the Lightbeam add-on.

**Comment by karandhankhar** [comment]
Vodafone page is openning by default i dont this page, opennin by default.

**Comment by karandhankhar** [comment]
do suggest duck buck go
