### ISSUE TITLE
on install, open "first run" page in background

### ISSUE THREAD

**Issue by monicachew** [mozilla/lightbeam#659]
This should be a simple change: instead of https://github.com/mozilla/lightbeam/blob/master/lib/main.js#L69, we can do

tabs.open({
  url: initialPageUrl,
  inBackground: true
});

@fmarier Do you think this is acceptable behavior in the regular build? If so we should go ahead and do it, it would be the easiest thing to fix @Verdi's problem.

**Comment by monicachew** [comment]
A more complicated fix would be to import UITour.jsm and check if the selectedBrowser was tourBrowsersByWindow. I doubt this is worth it.

**Comment by fmarier** [comment]
That's probably ok to do for everyone.

In theory the first run page should help users understand what Lightbeam is and how to use it, but in practice (at least based on the feedback we receive daily), it doesn't really work.
