### ISSUE TITLE
Add "uninstall Lightbeam" link just above the feedback link

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#665]
On the feedback list, there are people asking for help uninstalling Lightbeam every day.

We should add an "uninstall Lightbeam" link (pointing to [SUMO](https://support.mozilla.org/kb/disable-or-remove-add-ons)) next to the "give us feedback" link.

Alternatively, we could have a dialog popup when people click on "give us feedback" and that would have two links:

* Uninstall Lightbeam (instructions)
* Email us

**Comment by monicachew** [comment]
Great idea!

**Comment by maithuvenkatesh** [comment]
I've forked the project and added this link. However I forgot to create a separate branch for my previous PR to lightbeam (https://github.com/mozilla/lightbeam/pull/695). So, I can't submit this until the previous PR is accepted/rejected unless you'd like me to push both together? Please advice.
