### ISSUE TITLE
CFX is no more, prepare for JPM

### ISSUE THREAD

**Issue by erikvold** [mozilla/lightbeam#669]
The Mozilla add-on sdk team, myself included, has decided to discontinue the `cfx` python based cli, we've replaced it with a far leaner `jpm` nodejs based cli, you can install it with `npm install jpm -g`, and try it with `jpm -h`.

Add-ons made with `jpm` will only work on Nightly at the moment, so you'll have to consider that when deciding when to switch.  The plus side is that you can run your test suite on travis with `jpm` :)

For more information:

* http://work.erikvold.com/jetpack/2014/08/07/cfx-to-jpm.html
* http://work.erikvold.com/jetpack-pro-tip/2014/10/18/using-jpm-on-travis.html
* https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm
* https://github.com/mozilla/jpm

**Comment by monicachew** [comment]
Thanks for letting us know, Erik. What version are you targeting for jpm to be compatible with GA?

**Comment by erikvold** [comment]
Fx 38

**Comment by erikvold** [comment]
https://blog.mozilla.org/addons/2015/02/26/jpm-replaces-cfx-for-firefox-38/
