### ISSUE TITLE
Option to deactivate the animation

### ISSUE THREAD

**Issue by heubergen** [mozilla/lightbeam#673]
When I look to the Graph with my Daily or Weekly data the animation are really terrible because the framerate drop out to 5-10fps.

I think the hole problem could be minimized if theres a option to deactivate the animation.

**Comment by jonathanKingston** [comment]
We have since updated to 2.0.0, can you check if the performance has been fixed? Many features have changed however you might want to track the new repo here: https://github.com/mozilla/lightbeam-we
