### ISSUE TITLE
Option to activate upload to http://lightbeamdb.org

### ISSUE THREAD

**Issue by HugoPoi** [mozilla/lightbeam#676]
* Where is the option to activate upload to http://lightbeamdb.org ? has existed ?

* Lightbeamdb.org is empty ?

* `http://lightbeamdb.org/getData?name=http://www.google.fr` return `{}`

**Comment by fmarier** [comment]
That option has been removed and `lightbeamdb.org` is being decommissioned, that's why it's not working anymore. We are in the middle of updating the about pages to remove any mentions of that site.
