### ISSUE TITLE
Use a graph drawing library

### ISSUE THREAD

**Issue by mdamien** [mozilla/lightbeam#681]
You could use https://github.com/Linkurious/linkurious.js/ (a interaction-oriented fork of sigma.js), http://maurizzzio.github.io/greuler/ or something else.

It would fix a few customization, performance and interaction related issues.

**Comment by jonathanKingston** [comment]
We have since moved to: https://github.com/mozilla/lightbeam-we and we use canvas drawing to improve the perf.
