### ISSUE TITLE
Total failure on e10s

### ISSUE THREAD

**Issue by Marsfan** [mozilla/lightbeam#687]
I know things about e10s have been posted before, but all the bugs just say that buttons don't work under it. 

For me, nothing at all works under it. All e10s pages do not get any data sent to lightbeam. The whole thing was black until I loaded the same pages in a non-e10s window. 

Close this if it is a repeat, just throwing in my two cents.

**Comment by fmarier** [comment]
Yeah, it needs to be fixed for e10s, it doesn't work at all. The bug tracking that is https://bugzilla.mozilla.org/show_bug.cgi?id=1053007

**Comment by Marsfan** [comment]
Ok, I'm closing this because it seems to be nothing but a repeat. 
Sigh, if only I knew firefox plugin coding, I'd love to help
