### ISSUE TITLE
Donate your lightbeamData.json for research

### ISSUE THREAD

**Issue by hiromipaw** [mozilla/lightbeam#704]
Hello,

I am a researcher in web privacy at UPC in Barcelona, Spain. My public profile can be accessed at: http://hiromipaw.github.io/.

Recently I have been working on a study of how web sites track users and I would like to analyse lightbeam data of real users.

Would you be willing to donate your lightbeamData.json exported from your browser? If so maybe you would like to consider to send me a pull request on the following repository: https://github.com/hiromipaw/public-lightbeam-data

Once shared this data is public, so please make sure that you are not revealing anything too sensitive.

A preliminary article on this was just presented this past September at DPM 2015: http://hiromipaw.github.io/typeinst.pdf

**Comment by jonathanKingston** [comment]
The format has since changed in our new 2.0.0 release here: https://github.com/mozilla/lightbeam-we

Closing as this repo won't be active any longer.
