### ISSUE TITLE
Check out before and after!

### ISSUE THREAD

**Issue by dev-brother** [mozilla/lightbeam#707]
This tool is very useful indeed. Attached is before and after implementing some core security tweaks to firefox as well as hosts. Combination of a custom user.js, a collection of opensource addons and a vigorous hosts file.

Before
![lightbeambefore](https://cloud.githubusercontent.com/assets/1690415/11165161/302860b0-8b10-11e5-9164-6d5a73225456.jpg)
After
![lightbeamafter](https://cloud.githubusercontent.com/assets/1690415/11165164/3dd5e070-8b10-11e5-9bf7-6dcd6cd1993d.jpg)

Thanks again

**Comment by fmarier** [comment]
Very nice!
