### ISSUE TITLE
WebVR view

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#708]
In addition to the list view and the graph view, we should have a WebVR view so that you can hear tracking drones flying over you and peak at sneaky critters following you around.

![trackers](https://cloud.githubusercontent.com/assets/167821/11575816/e4960bc2-99c7-11e5-9b29-11d9677b1887.png)

**Comment by dethe** [comment]
:+1:

**Comment by erikvold** [comment]
awesome idea!

**Comment by jonathanKingston** [comment]
We have a bug tracking for this: https://github.com/mozilla/lightbeam-we and there is movement there too.
