### ISSUE TITLE
"Globe" panel doesn't work anymore

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#711]
When clicking on a domain in the Graph view, the "globe" panel (from which one can block individual sites) no longer shows up.

I tested this in Iceweasel 38.7.1 an Firefox 45.0.1. Maybe something went bad when the add-on was re-signed or re-published by AMO?

Testing older versions of the add-on might shed some light on this.

**Comment by fmarier** [comment]
Based on the feedback I have received, it broke around 24 March 2016 (Pacific time).

**Comment by msches** [comment]
I've the same problem with lightbeam installation 1.3.0.1 an firefox 45.0.1, but a few days before it works without any problems!?

**Comment by msches** [comment]
After re-installation the problem still exist ...

**Comment by fmarier** [comment]
It seems to work fine in 52.
