### ISSUE TITLE
Graph view broken

### ISSUE THREAD

**Issue by luukaaszq** [mozilla/lightbeam#715]
Lightbeam show only connections

![lightbeam](https://cloud.githubusercontent.com/assets/11009097/18726356/5dd83768-8044-11e6-827c-eff0fcbca3e2.png)

**Comment by fmarier** [comment]
Which version of Firefox are you using?

**Comment by luukaaszq** [comment]
49.0

**Comment by fmarier** [comment]
I can't reproduce this. It works fine for me on 49.0.
