### ISSUE TITLE
UI elements are overlapped.

### ISSUE THREAD

**Issue by manfredosanchez** [mozilla/lightbeam#716]
The elements at the bottom of the Graph page are overlapped.

![2016-11-30 12_08_28-lightbeam](https://cloud.githubusercontent.com/assets/4485480/20760285/f3ce3de8-b6f5-11e6-81a7-90de0796e679.png)

No zoom applied.

**Comment by collectorgeneral** [comment]
Same issue here.

**Comment by collectorgeneral** [comment]
I am starting to believe that this is applicable for low resolution monitors. I checked on my desktop monitor (1920x1080) and it looks completely fine. On my laptop (1336x768) however, it is overlapped. 
Any devs can take a look at this and confirm please?

**Comment by collectorgeneral** [comment]
Actually nvm, it looks like they fixed it. I checked today and everything is fine. 

![screenshot from 2017-02-07 20-25-37](https://cloud.githubusercontent.com/assets/15972594/22717853/beb99f1c-ed73-11e6-97f1-7a0df9808976.png)

I think this issue can be closed?
