### ISSUE TITLE
install fails on Nightly 54.0 & windows

### ISSUE THREAD

**Issue by kyodev** [mozilla/lightbeam#720]
It seems that lightbeam does not install correctly with Nightly 54.0
Tested on 2 French users, on win7 and win8.1
see: [french forum mozFr](https://forums.mozfr.org/viewtopic.php?f=24&t=132612&p=838485#p838483)

* Visible in about: addons
* No open post-installation page
* No icon to reach the graphics display
* No item "show lightbeam" in the tools menu

**Comment by fmarier** [comment]
Fixed by https://github.com/mozilla/lightbeam/pull/717.

**Comment by kyodev** [comment]
I confirm, all is ok
