### ISSUE TITLE
Convert lightbeam into a web extension

### ISSUE THREAD

**Issue by erikvold** [mozilla/lightbeam#723]
What's the plan to make this a web extension? since Firefox is making everything else useless now.  Or is this the end for lightbeam?

**Comment by fmarier** [comment]
It's tracked in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1342681

**Comment by jonathanKingston** [comment]
See here: https://github.com/mozilla/lightbeam-we

This has now landed thanks to our Outreachy interns.
