### ISSUE TITLE
Clearing all Blocked Sites

### ISSUE THREAD

**Issue by ghost** [mozilla/lightbeam#724]
Ok,so maybe I overdid the site blocking,but... I now find the some sites no longer work correctly(Notably Amazon which now has large areas of black screen) even after I re-set all my blocked sites to normal. I have tried reseting the data and uninstalling  Lightbeam to no avail. Oddly if I re-install Lightbeam all my sites are still listed. So, the question is how can I reinstate Amazon to its proper state?

**Comment by jonathanKingston** [comment]
This has since been removed as a feature in 2.0.0. Updating to: https://github.com/mozilla/lightbeam-we which should happen automatically should fix this.

We might add back in that feature later.
