### ISSUE TITLE
Where does Lightbeam store its data ?

### ISSUE THREAD

**Issue by uihdff** [mozilla/lightbeam#727]
Running Firefox 56.0.2 and Lightbeam 2.0.4.

Where does Lightbeam store its data that ?

Firefox is configured to delete all history when the browser exits. When the browser restarts, the tracking data Lightbeam displays is still there.

**Comment by Valenchak** [comment]
Great news

**Comment by uihdff** [comment]
How is that great news ?

**Comment by uihdff** [comment]
Is Lightbeam data stored as LSOs ?

**Comment by jonathanKingston** [comment]
The data is stored in IndexedDb in the extension which makes it be treated like browser preferences and internal data, we have a manual delete button for users who want to clear it.

**Comment by uihdff** [comment]
As a feature request, it would be useful to have an option for Lightbeam's data to be deleted when the browser is closed.
