### ISSUE TITLE
Collusion has incompatibilities with other privacy add-ons

### ISSUE THREAD

**Issue by jonoxia** [mozilla/lightbeam#75]
Mentioned in user reviews of the add-on. See https://addons.mozilla.org/en-US/firefox/addon/collusion/reviews/

Several users have reported problems using Collusion with:

Ghostery
DNT Plus
Adblock Plus
RefControl

Need to investigate and figure out what the exact problems are, then reproduce them.

**Comment by jonathanKingston** [comment]
The extension has since been completely rewritten, give it a try again and raise issues here: https://github.com/mozilla/lightbeam-we

Thank you for raising!
